#!/usr/bin/env node
/**
 * Walks `cloud/api/` looking for `route.ts` / `route.tsx` files and emits
 * `src/_router.generated.ts` — one import + one `app.route()` per leaf.
 *
 * Path mapping mirrors Next.js App Router:
 *   api/foo/route.ts            -> /api/foo
 *   api/foo/[id]/route.ts       -> /api/foo/:id
 *   api/foo/[...slug]/route.ts  -> /api/foo/*
 *   api/(group)/foo/route.ts    -> /api/foo   (group segments dropped)
 *
 * Re-run after adding or deleting any route file. Idempotent.
 */

import { promises as fs } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const API_ROOT = resolve(__dirname, "..");
const OUT_FILE = resolve(__dirname, "_router.generated.ts");

async function* walk(dir) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip our own src/ tree, node_modules, and dotfiles.
      if (entry.name === "src" || entry.name === "node_modules" || entry.name.startsWith(".")) {
        continue;
      }
      yield* walk(full);
    } else if (entry.isFile() && (entry.name === "route.ts" || entry.name === "route.tsx")) {
      yield full;
    }
  }
}

function fileToHttpPath(filePath) {
  // filePath: <repo>/cloud/api/foo/[id]/route.ts
  // We want: /api/foo/:id
  const rel = relative(API_ROOT, filePath); // e.g. "foo/[id]/route.ts"
  const segments = rel.split("/").slice(0, -1); // drop "route.ts"
  const out = ["/api"];
  for (const seg of segments) {
    if (seg.startsWith("(") && seg.endsWith(")")) continue; // route group
    if (seg.startsWith("[...") && seg.endsWith("]")) {
      out.push("*");
      continue;
    }
    if (seg.startsWith("[") && seg.endsWith("]")) {
      out.push(`:${seg.slice(1, -1)}`);
      continue;
    }
    out.push(seg);
  }
  return out.join("/").replace(/\/+/g, "/");
}

function importIdent(filePath) {
  const rel = relative(API_ROOT, filePath).replace(/\.tsx?$/, "");
  return (
    "_route_" +
    rel
      .replace(/\//g, "_")
      .replace(/\[\.\.\.([^\]]+)\]/g, "splat_$1")
      .replace(/\[([^\]]+)\]/g, "p_$1")
      .replace(/\(([^)]+)\)/g, "g_$1")
      .replace(/[^a-zA-Z0-9_]/g, "_")
  );
}

function importPath(filePath) {
  const rel = relative(__dirname, filePath).replace(/\.tsx?$/, "");
  // Hono / TS Bundler resolution: prefer the relative path so we don't depend
  // on tsconfig path aliases for the generated file.
  return rel.startsWith(".") ? rel : `./${rel}`;
}

async function main() {
  const files = [];
  for await (const f of walk(API_ROOT)) files.push(f);
  files.sort();

  // Group by HTTP path so duplicate paths can be flagged.
  const seen = new Map();
  const entries = [];
  for (const f of files) {
    const path = fileToHttpPath(f);
    if (seen.has(path)) {
      console.warn(`[codegen] duplicate route path ${path} from ${f} and ${seen.get(path)}`);
    }
    seen.set(path, f);
    entries.push({ path, ident: importIdent(f), import: importPath(f) });
  }

  const banner = [
    "/**",
    " * AUTO-GENERATED by src/_generate-router.mjs — do not edit by hand.",
    " * Re-run `bun run codegen` after adding or removing a route.ts file.",
    " *",
    `* ${entries.length} routes mounted.`,
    " */",
    "",
    "/* eslint-disable */",
    "// @ts-nocheck",
    "",
    'import type { Hono } from "hono";',
    'import type { AppEnv } from "./lib/context";',
    "",
  ].join("\n");

  const imports = entries.map((e) => `import ${e.ident} from "${e.import}";`).join("\n");
  const mounts = entries.map((e) => `  app.route(${JSON.stringify(e.path)}, ${e.ident} as any);`).join("\n");

  const body = [
    banner,
    imports,
    "",
    "export function mountRoutes(app: Hono<AppEnv>): void {",
    mounts,
    "}",
    "",
  ].join("\n");

  await fs.writeFile(OUT_FILE, body, "utf8");
  console.log(`[codegen] wrote ${OUT_FILE} (${entries.length} routes)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
