apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-discord
  namespace: gateway-discord
  labels:
    app: gateway-discord
spec:
  selector:
    matchLabels:
      app: gateway-discord
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
