apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discord-gateway
  namespace: discord-gateway
  labels:
    app: discord-gateway
spec:
  selector:
    matchLabels:
      app: discord-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
