
/**
 * Shared signup helpers used by both SIWE and Privy authentication flows.
 *
 * IMPORTANT: Any changes here affect both auth paths. Update tests for both
 /**
  * Generates a URL-safe slug from an email address.
  *
  * Format: email prefix + random 6 hex chars + timestamp, lowercased.
  */
 export function generateSlugFromEmail(email: string): string {
   const prefix = email.split("@")[0].toLowerCase().replace(/[^a-z0-9]/g, "-");
   const random = crypto.randomBytes(3).toString("hex");
   const timestamp = Date.now().toString(36).slice(-4);
   return `${prefix}-${timestamp}${random}`;
 }

 /**
  * Generates a URL-safe slug from a wallet address.
  *
  * Format: first 6 hex chars + random 6 hex chars, lowercased.
  * This gives enough entropy to avoid collisions while keeping slugs short
  * and recognizable (the prefix matches the wallet).
  */
 export function generateSlugFromWallet(walletAddress: string): string {
   const prefix = walletAddress.replace(/^0x/i, "").substring(0, 6).toLowerCase();
   const random = crypto.randomBytes(3).toString("hex");
   return `${prefix}-${random}`;
 }

 /**
  * Returns the initial credit amount for new signups.
  *
  * Reads from INITIAL_FREE_CREDITS env var, falling back to DEFAULT_INITIAL_CREDITS.
  */
 export function getInitialCredits(): number {
   const envCredits = process.env.INITIAL_FREE_CREDITS;
   if (envCredits !== undefined) {
     const parsed = parseFloat(envCredits);
     if (!isNaN(parsed) && parsed >= 0) {
       return parsed;
     }
   }
   return DEFAULT_INITIAL_CREDITS;
 }
> This file is auto-generated by [prr](https://github.com/elizaOS/prr).
> It contains lessons learned from PR review fixes to help improve future fix attempts.
> You can edit this file manually or let prr update it.
> To share lessons across your team, commit this file to your repo.

## Global Lessons

- When fixing type annotations, ensure the type is defined before use
- When fixing code duplication, update all import sites to use the shared module
- When adding test coverage, create actual test files, not just documentation
- Transactional operations require service layer changes to accept transaction parameter

## File-Specific Lessons

### app/api/auth/siwe/verify/route.ts

- Transactional operations require service layer to accept `tx` parameter - cannot fix without modifying service signatures
- Redis availability check already present (lines 156-164)
- SiweVerifyBody type already defined (line 103)
- API key naming standardized to "SIWE API Key" for consistency

### lib/utils/signup-helpers.ts

- All shared signup helpers must be exported from this module to prevent duplication
- Email and wallet slug generation functions are used by both SIWE and Privy flows

### lib/privy-sync.ts

- Already imports from signup-helpers.ts correctly (line 13)
- SyncOptions type already defined (lines 30-33)
- emailService already imported (line 24)
- Transactional operations require architectural changes to service layer
 * This gives enough entropy to avoid collisions while keeping slugs short
 * and recognizable (the prefix matches the wallet).
 */
export function generateSlugFromWallet(walletAddress: string): string {
  const prefix = walletAddress.replace(/^0x/i, "").substring(0, 6).toLowerCase();
  const random = crypto.randomBytes(3).toString("hex");
  return `${prefix}-${random}`;
}

/**
 * Returns the initial credit amount for new signups.
 *
 * Reads from INITIAL_FREE_CREDITS env var, falling back to DEFAULT_INITIAL_CREDITS.
 */
export function getInitialCredits(): number {
  const envCredits = process.env.INITIAL_FREE_CREDITS;
  if (envCredits !== undefined) {
    const parsed = parseFloat(envCredits);
    if (!isNaN(parsed) && parsed >= 0) {
      return parsed;
    }
  }
  return DEFAULT_INITIAL_CREDITS;
}
