/**
 * Unified Seed Script for Local Development
 *
 * Creates a complete development environment with:
 * - One test organization with credits
 * - One test user (with wallet for Privy)
 * - Multiple apps: app, todoapp
 * - API keys for each app
 * - Todo assistant agent with MCP
 * - Storage collections for todo app
 *
 * This is the recommended seed for local dev - sets up everything at once.
 *
 * Usage:
 *   bun run db:seed:dev
 *   bun run db:seed:dev --force  # Regenerate API keys
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { db } from "../db/client";
import * as fs from "fs";
import * as path from "path";
import { users } from "../db/schemas/users";
import { organizations } from "../db/schemas/organizations";
import { apps, appUsers, type NewApp } from "../db/schemas/apps";
import { apiKeys } from "../db/schemas/api-keys";
import { userCharacters, type NewUserCharacter } from "../db/schemas/user-characters";
import { appCollections, type CollectionSchema, type CollectionIndex } from "../db/schemas/app-storage";
import { eq, and } from "drizzle-orm";
import crypto from "crypto";

// ============================================
// Configuration
// ============================================

// Known hardhat test wallet - standard mnemonic
const TEST_WALLET_ADDRESS = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";

const ORG_CONFIG = {
  name: "Dev Organization",
  slug: "dev-org",
  creditBalance: "500.00", // $500 test credits
};

const USER_CONFIG = {
  email: "dev@eliza.ai",
  name: "Dev User",
  nickname: "devuser",
  walletAddress: TEST_WALLET_ADDRESS.toLowerCase(),
};

const APP_CONFIG = {
  name: "Eliza App",
  slug: "eliza-app",
  description: "Character creator app",
  appUrl: "http://localhost:3001",
  allowedOrigins: [
    "http://localhost:3001",
    "http://localhost:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3000",
  ],
  features: {
    chat: true,
    image: true,
    video: false,
    voice: true,
    agents: true,
    embedding: true,
  },
  envFile: "app/.env.local",
  port: 3001,
};

const TODOAPP_CONFIG = {
  name: "Eliza Todo",
  slug: "eliza-todo",
  description: "AI-powered task management with gamification",
  appUrl: "http://localhost:3002",
  allowedOrigins: [
    "http://localhost:3002",
    "http://localhost:3000",
    "http://127.0.0.1:3002",
    "http://127.0.0.1:3000",
  ],
  features: {
    chat: true,
    image: false,
    video: false,
    voice: false,
    agents: true,
    embedding: false,
  },
  envFile: "todo-app/.env.local",
  port: 3002,
};

const API_KEY_PERMISSIONS = [
  "apps.access",
  "generation.all",
  "agents.all",
  "chat.all",
  "storage.all",
  "affiliate:create-character",
];

// ============================================
// Helpers
// ============================================

function generateApiKey(): { key: string; hash: string; prefix: string; lastFour: string } {
  const key = `eliza_${crypto.randomBytes(32).toString("hex")}`;
  const hash = crypto.createHash("sha256").update(key).digest("hex");
  const prefix = key.substring(0, 12);
  const lastFour = key.slice(-4);
  return { key, hash, prefix, lastFour };
}

function writeEnvFile(filePath: string, apiKey: string, cloudUrl: string, appUrl: string): void {
  const fullPath = path.join(process.cwd(), filePath);
  const dir = path.dirname(fullPath);
  
  if (!fs.existsSync(dir)) {
    console.log(`  ⚠ Directory ${dir} does not exist, skipping env file`);
    return;
  }

  const content = `# Generated by seed-dev.ts
# ${new Date().toISOString()}

# API Key for Eliza Cloud
ELIZA_CLOUD_API_KEY=${apiKey}

# Cloud API URL
NEXT_PUBLIC_CLOUD_URL=${cloudUrl}

# App URL (for callbacks)
NEXT_PUBLIC_APP_URL=${appUrl}
`;

  fs.writeFileSync(fullPath, content);
  console.log(`  ✓ Written ${filePath}`);
}

// ============================================
// Main Seed Function
// ============================================

async function seedDev() {
  const forceRegenerate = process.argv.includes("--force");
  
  console.log("\n" + "=".repeat(60));
  console.log("  Eliza Cloud - Local Development Seed");
  console.log("=".repeat(60) + "\n");

  // ============================================
  // 1. Organization
  // ============================================
  console.log("[1/7] Organization...");
  let org = await db.query.organizations.findFirst({
    where: eq(organizations.slug, ORG_CONFIG.slug),
  });

  if (!org) {
    const [newOrg] = await db
      .insert(organizations)
      .values({
        name: ORG_CONFIG.name,
        slug: ORG_CONFIG.slug,
        credit_balance: ORG_CONFIG.creditBalance,
      })
      .returning();
    org = newOrg;
    console.log(`  ✨ Created: ${org?.id}`);
  } else {
    // Top up credits if low
    const currentBalance = parseFloat(org.credit_balance ?? "0");
    if (currentBalance < 100) {
      await db
        .update(organizations)
        .set({ credit_balance: ORG_CONFIG.creditBalance })
        .where(eq(organizations.id, org.id));
      console.log(`  ♻️  Reused + topped up credits: ${org.id}`);
    } else {
      console.log(`  ♻️  Reused: ${org.id}`);
    }
  }

  if (!org) throw new Error("Failed to create organization");

  // ============================================
  // 2. User
  // ============================================
  console.log("\n[2/7] User...");
  let user = await db.query.users.findFirst({
    where: eq(users.wallet_address, USER_CONFIG.walletAddress),
  });

  if (!user) {
    const [newUser] = await db
      .insert(users)
      .values({
        email: USER_CONFIG.email,
        name: USER_CONFIG.name,
        nickname: USER_CONFIG.nickname,
        wallet_address: USER_CONFIG.walletAddress,
        wallet_chain_type: "ethereum",
        wallet_verified: true,
        organization_id: org.id,
        privy_did: `did:privy:dev-${Date.now()}`,
        role: "owner",
        is_anonymous: false,
        is_active: true,
      })
      .returning();
    user = newUser;
    console.log(`  ✨ Created: ${user?.id}`);
  } else {
    // Ensure org link
    if (user.organization_id !== org.id) {
      await db
        .update(users)
        .set({ organization_id: org.id })
        .where(eq(users.id, user.id));
    }
    console.log(`  ♻️  Reused: ${user.id}`);
  }

  if (!user) throw new Error("Failed to create user");

  // ============================================
  // 3. App
  // ============================================
  console.log("\n[3/7] App...");
  let app = await db.query.apps.findFirst({
    where: eq(apps.slug, APP_CONFIG.slug),
  });

  let appKey: string | null = null;

  if (!app) {
    // Create API key first
    const { key, hash, prefix, lastFour } = generateApiKey();
    appKey = key;

    const [newApiKey] = await db
      .insert(apiKeys)
      .values({
        name: `${APP_CONFIG.name} API Key`,
        description: "Auto-generated for app",
        key: key,
        key_hash: hash,
        key_prefix: prefix,
        organization_id: org.id,
        user_id: user.id,
        permissions: API_KEY_PERMISSIONS,
        is_active: true,
      })
      .returning();

    const appData: NewApp = {
      name: APP_CONFIG.name,
      slug: APP_CONFIG.slug,
      description: APP_CONFIG.description,
      organization_id: org.id,
      created_by_user_id: user.id,
      app_url: APP_CONFIG.appUrl,
      allowed_origins: APP_CONFIG.allowedOrigins,
      api_key_id: newApiKey.id,
      features_enabled: APP_CONFIG.features,
      app_type: "app",
      is_active: true,
      enabled: true,
    };

    const [newApp] = await db.insert(apps).values(appData).returning();
    app = newApp;
    console.log(`  ✨ Created: ${app?.id}`);
    writeEnvFile(APP_CONFIG.envFile, appKey, "http://localhost:3000", APP_CONFIG.appUrl);
  } else {
    // Update allowed origins
    await db
      .update(apps)
      .set({ allowed_origins: APP_CONFIG.allowedOrigins, organization_id: org.id })
      .where(eq(apps.id, app.id));

    if (forceRegenerate && app.api_key_id) {
      // Regenerate key
      const { key, hash, prefix } = generateApiKey();
      appKey = key;
      await db
        .update(apiKeys)
        .set({ key: key, key_hash: hash, key_prefix: prefix, updated_at: new Date() })
        .where(eq(apiKeys.id, app.api_key_id));
      console.log(`  🔄 Regenerated API key: ${prefix}...`);
      writeEnvFile(APP_CONFIG.envFile, appKey, "http://localhost:3000", APP_CONFIG.appUrl);
    } else {
      console.log(`  ♻️  Reused: ${app.id}`);
    }
  }

  if (!app) throw new Error("Failed to create app");

  // Link user to app
  const existingAppUser = await db.query.appUsers.findFirst({
    where: and(eq(appUsers.app_id, app.id), eq(appUsers.user_id, user.id)),
  });
  if (!existingAppUser) {
    await db.insert(appUsers).values({ app_id: app.id, user_id: user.id, signup_source: "seed" });
  }

  // ============================================
  // 4. Todo App
  // ============================================
  console.log("\n[4/7] Todo App...");
  let todoapp = await db.query.apps.findFirst({
    where: eq(apps.slug, TODOAPP_CONFIG.slug),
  });

  let todoappKey: string | null = null;

  if (!todoapp) {
    // Create API key first
    const { key, hash, prefix, lastFour } = generateApiKey();
    todoappKey = key;

    const [newApiKey] = await db
      .insert(apiKeys)
      .values({
        name: `${TODOAPP_CONFIG.name} API Key`,
        description: "Auto-generated for todo app",
        key: key,
        key_hash: hash,
        key_prefix: prefix,
        organization_id: org.id,
        user_id: user.id,
        permissions: API_KEY_PERMISSIONS,
        is_active: true,
      })
      .returning();

    const appData: NewApp = {
      name: TODOAPP_CONFIG.name,
      slug: TODOAPP_CONFIG.slug,
      description: TODOAPP_CONFIG.description,
      organization_id: org.id,
      created_by_user_id: user.id,
      app_url: TODOAPP_CONFIG.appUrl,
      allowed_origins: TODOAPP_CONFIG.allowedOrigins,
      api_key_id: newApiKey.id,
      features_enabled: TODOAPP_CONFIG.features,
      app_type: "app",
      is_active: true,
      enabled: true,
    };

    const [newApp] = await db.insert(apps).values(appData).returning();
    todoapp = newApp;
    console.log(`  ✨ Created: ${todoapp?.id}`);
    writeEnvFile(TODOAPP_CONFIG.envFile, todoappKey, "http://localhost:3000", TODOAPP_CONFIG.appUrl);
  } else {
    // Update allowed origins
    await db
      .update(apps)
      .set({ allowed_origins: TODOAPP_CONFIG.allowedOrigins, organization_id: org.id })
      .where(eq(apps.id, todoapp.id));

    if (forceRegenerate && todoapp.api_key_id) {
      // Regenerate key
      const { key, hash, prefix } = generateApiKey();
      todoappKey = key;
      await db
        .update(apiKeys)
        .set({ key: key, key_hash: hash, key_prefix: prefix, updated_at: new Date() })
        .where(eq(apiKeys.id, todoapp.api_key_id));
      console.log(`  🔄 Regenerated API key: ${prefix}...`);
      writeEnvFile(TODOAPP_CONFIG.envFile, todoappKey, "http://localhost:3000", TODOAPP_CONFIG.appUrl);
    } else {
      console.log(`  ♻️  Reused: ${todoapp.id}`);
    }
  }

  if (!todoapp) throw new Error("Failed to create todoapp");

  // Link user to todoapp
  const existingTodoappUser = await db.query.appUsers.findFirst({
    where: and(eq(appUsers.app_id, todoapp.id), eq(appUsers.user_id, user.id)),
  });
  if (!existingTodoappUser) {
    await db.insert(appUsers).values({ app_id: todoapp.id, user_id: user.id, signup_source: "seed" });
  }

  // ============================================
  // 5. Task Assistant Agent
  // ============================================
  console.log("\n[5/7] Task Assistant Agent...");
  let agent: { id: string } | null = null;
  
  try {
    agent = await db.query.userCharacters.findFirst({
      where: and(
        eq(userCharacters.name, "Task Assistant"),
        eq(userCharacters.organization_id, org.id)
      ),
    });
  } catch {
    console.log("  ⚠ Schema mismatch - skipping agent check (run migrations)");
  }

  if (!agent) {
    try {
      const characterData: NewUserCharacter = {
      organization_id: org.id,
      user_id: user.id,
      name: "Task Assistant",
      username: "task-assistant",
      system: `You are a friendly and motivating task management assistant. Your role is to help users:

1. Create and organize tasks (daily habits, one-off tasks, aspirational goals)
2. Stay motivated with gamification (points, streaks, levels)
3. Build productive habits
4. Prioritize work effectively

When users ask to create tasks, extract:
- Task name (required)
- Type: "daily" (recurring), "one-off" (single), or "aspirational" (long-term goals)
- Priority: 1 (highest) to 4 (lowest) for one-off tasks
- Urgency: whether it's time-sensitive
- Due date: if mentioned

Be encouraging and celebrate completions! Use the gamification system to motivate users.`,
      bio: [
        "I help you manage tasks, build habits, and stay productive.",
        "Let me help you organize your day and achieve your goals.",
      ],
      message_examples: [
        [
          { user: "user", content: { text: "Add a task to review the quarterly report by Friday" } },
          {
            user: "Task Assistant",
            content: {
              text: "I've created a one-off task: 'Review quarterly report' with a due date of Friday. I've set it as priority 2 since it has a deadline. Would you like me to mark it as urgent?",
            },
          },
        ],
        [
          { user: "user", content: { text: "I want to exercise every morning" } },
          {
            user: "Task Assistant",
            content: {
              text: "Great goal! I've added 'Morning exercise' as a daily habit. You'll earn 10 base points each day you complete it, plus bonus points for maintaining your streak. Ready to build that habit? 💪",
            },
          },
        ],
      ],
      topics: ["productivity", "task management", "habits", "goals"],
      adjectives: ["helpful", "encouraging", "organized", "motivating"],
      style: {
        all: ["Be encouraging", "Celebrate completions", "Use gamification language"],
        chat: ["Be conversational", "Ask clarifying questions"],
      },
      plugins: ["@elizaos/plugin-mcp"],
      settings: {
        model: "claude-sonnet-4-20250514",
        voice: { model: "en_US-hfc_female-medium" },
        mcp: {
          servers: {
            "todo-tasks": {
              type: "http",
              url: "/api/mcp/todoapp",
            },
          },
        },
      },
      character_data: {},
      source: "app",
      is_public: true,
      is_template: false,
      a2a_enabled: true,
      mcp_enabled: true,
    };

      const [newAgent] = await db.insert(userCharacters).values(characterData).returning();
      agent = newAgent;
      console.log(`  ✨ Created: ${agent?.id}`);
    } catch (e) {
      console.log("  ⚠ Failed to create agent (schema mismatch?) - skipping");
      console.log(`    ${e instanceof Error ? e.message : "Unknown error"}`);
    }
  } else {
    console.log(`  ♻️  Reused: ${agent.id}`);
  }

  // ============================================
  // 6. Todo Storage Collections
  // ============================================
  console.log("\n[6/7] Todo Storage Collections...");

  try {
    // Tasks collection
    const tasksCollection = await db.query.appCollections.findFirst({
      where: and(
        eq(appCollections.app_id, todoapp.id),
        eq(appCollections.name, "tasks")
      ),
    });

    if (!tasksCollection) {
      const tasksSchema: CollectionSchema = {
        type: "object",
        properties: {
          name: { type: "string", description: "Task name" },
          type: { type: "string", description: "Task type: daily, one-off, aspirational" },
          priority: { type: "integer", description: "Priority 1-4" },
          urgent: { type: "boolean", description: "Is urgent" },
          completed: { type: "boolean", description: "Is completed" },
          metadata: { type: "object", description: "Task metadata" },
        },
        required: ["name", "type", "completed"],
      };

      const tasksIndexes: CollectionIndex[] = [
        { field: "type", type: "string" },
        { field: "completed", type: "boolean" },
      ];

      await db.insert(appCollections).values({
        app_id: todoapp.id,
        name: "tasks",
        description: "Todo tasks storage",
        schema: tasksSchema,
        indexes: tasksIndexes,
      });
      console.log("  ✨ Created tasks collection");
    } else {
      console.log("  ♻️  Reused tasks collection");
    }

    // User points collection
    const pointsCollection = await db.query.appCollections.findFirst({
      where: and(
        eq(appCollections.app_id, todoapp.id),
        eq(appCollections.name, "user_points")
      ),
    });

    if (!pointsCollection) {
      const pointsSchema: CollectionSchema = {
        type: "object",
        properties: {
          currentPoints: { type: "integer", description: "Current points" },
          totalEarned: { type: "integer", description: "Total points earned" },
          streak: { type: "integer", description: "Current streak" },
          history: { type: "array", description: "Points history" },
        },
        required: ["currentPoints", "totalEarned"],
      };

      await db.insert(appCollections).values({
        app_id: todoapp.id,
        name: "user_points",
        description: "User points and gamification",
        schema: pointsSchema,
        indexes: [],
      });
      console.log("  ✨ Created user_points collection");
    } else {
      console.log("  ♻️  Reused user_points collection");
    }
  } catch {
    console.log("  ⚠ Collections table not found - will be created on first use");
  }

  // ============================================
  // 7. Summary
  // ============================================
  console.log("\n[7/7] Complete!");

  console.log("\n" + "=".repeat(60));
  console.log("  🎉 Development Environment Ready!");
  console.log("=".repeat(60));

  console.log("\n📋 Test User:");
  console.log(`   User ID:      ${user.id}`);
  console.log(`   Email:        ${USER_CONFIG.email}`);
  console.log(`   Wallet:       ${TEST_WALLET_ADDRESS}`);
  console.log(`   Org:          ${org.name} (${org.id})`);
  console.log(`   Credits:      $${ORG_CONFIG.creditBalance}`);

  console.log("\n📱 Apps:");
  console.log(`   App:      ${app.slug} (${app.id})`);
  console.log(`                 URL: ${APP_CONFIG.appUrl}`);
  console.log(`   Todo App:     ${todoapp.slug} (${todoapp.id})`);
  console.log(`                 URL: ${TODOAPP_CONFIG.appUrl}`);

  console.log("\n🤖 Agent:");
  console.log(`   Task Assistant: ${agent?.id}`);

  if (appKey || todoappKey) {
    console.log("\n🔑 API Keys written to:");
    if (appKey) console.log(`   ${APP_CONFIG.envFile}`);
    if (todoappKey) console.log(`   ${TODOAPP_CONFIG.envFile}`);
  }

  console.log("\n🚀 Quick Start:");
  console.log("   # Start cloud + all apps:");
  console.log("   bun run dev:all");
  console.log("");
  console.log("   # Or individually:");
  console.log("   bun run dev              # Cloud (port 3000)");
  console.log("   cd app && bun dev    # App (port 3001)");
  console.log("   cd todo-app && bun dev   # Todo App (port 3002)");

  console.log("\n🔐 Test Wallet (for Privy login):");
  console.log(`   Address: ${TEST_WALLET_ADDRESS}`);
  console.log('   Seed:    "test test test test test test test test test test test junk"');

  console.log("\n" + "=".repeat(60) + "\n");
}

// Run
seedDev()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Error:", error);
    process.exit(1);
  });

