import { NextRequest, NextResponse } from "next/server";
import { logger } from "@/lib/utils/logger";
import { requireAuthOrApiKey } from "@/lib/auth";
import { getKnowledgeService } from "@/lib/eliza/knowledge-service";
import type { UUID } from "@elizaos/core";
import { withRateLimit, RateLimitPresets } from "@/lib/middleware/rate-limit";
import { userContextService } from "@/lib/eliza/user-context";
import { RuntimeFactory } from "@/lib/eliza/runtime-factory";
import { AgentMode } from "@/lib/eliza/agent-mode-types";

export const maxDuration = 60;

interface UploadResult {
  id: string;
  filename: string;
  type: string;
  size: number;
  uploadedAt: number;
  status: string;
  fragmentCount?: number;
  error?: string;
}

/**
 * POST /api/v1/knowledge/upload-file
 * Uploads one or more files to the knowledge base.
 * Processes files and creates knowledge fragments for semantic search.
 *
 * @param req - Form data with files array and optional characterId.
 * @returns Upload results for each file including fragment counts.
 */
const MAX_BODY_SIZE = 10 * 1024 * 1024; // 10MB - Next.js default limit

async function handlePOST(req: NextRequest) {
  try {
    const authResult = await requireAuthOrApiKey(req);
    const { user } = authResult;

    // Parse form data with proper error handling for size limits
    let formData: FormData;
    try {
      formData = await req.formData();
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      
      // Check if it's a body size limit error
      if (errorMessage.includes("body") || errorMessage.includes("FormData") || errorMessage.includes("boundary")) {
        logger.warn("[KnowledgeUpload] Request body too large or malformed", {
          error: errorMessage,
        });
        return NextResponse.json(
          {
            error: "Upload too large",
            details: `Total upload size must be under ${MAX_BODY_SIZE / (1024 * 1024)}MB. Please upload smaller files or fewer files at once.`,
          },
          { status: 413 },
        );
      }
      throw error;
    }

    const files = formData.getAll("files") as File[];
    const characterId = formData.get("characterId") as string | null;

    // Build user context with ASSISTANT mode (required for knowledge plugin)
    const userContext = await userContextService.buildContext({
      user,
      apiKey: authResult.apiKey,
      isAnonymous: false,
      agentMode: AgentMode.ASSISTANT,
    });

    if (characterId) {
      userContext.characterId = characterId;
    }

    // Create runtime with user-specific context (includes API key for embeddings)
    const runtimeFactory = RuntimeFactory.getInstance();
    const runtime = await runtimeFactory.createRuntimeForUser(userContext);

    const knowledgeService = await getKnowledgeService(runtime);

    if (!knowledgeService) {
      return NextResponse.json(
        { error: "Knowledge service not available" },
        { status: 503 },
      );
    }

    if (!files || files.length === 0) {
      return NextResponse.json(
        {
          error: "No files provided",
          details: "Please upload at least one file",
        },
        { status: 400 },
      );
    }

    // Process all files
    const results: UploadResult[] = await Promise.all(
      files.map(async (file) => {
        try {
          // Read file content and convert to base64
          const arrayBuffer = await file.arrayBuffer();
          const buffer = Buffer.from(arrayBuffer);
          const base64Content = buffer.toString("base64");
          const contentType = file.type || "application/octet-stream";

          // Add knowledge document (matching plugin-knowledge pattern exactly)
          // Use runtime.agentId for roomId, worldId, entityId (same as plugin)
          const result = await knowledgeService.addKnowledge({
            agentId: runtime.agentId,
            clientDocumentId: "" as UUID, // Auto-generated by service
            content: base64Content,
            contentType,
            originalFilename: file.name,
            worldId: runtime.agentId,
            roomId: runtime.agentId,
            entityId: runtime.agentId,
            metadata: {
              uploadedBy: user.id,
              uploadedAt: Date.now(),
              organizationId: user.organization_id,
              fileSize: file.size,
              fileName: file.name,
              filename: file.name, // Add both for compatibility
            },
          });

          return {
            id: result.clientDocumentId,
            filename: file.name,
            type: contentType,
            size: file.size,
            uploadedAt: Date.now(),
            fragmentCount: result.fragmentCount,
            status: "success",
          };
        } catch (fileError) {
          logger.error(`Error processing file ${file.name}:`, fileError);
          return {
            id: "",
            filename: file.name,
            type: file.type,
            size: file.size,
            uploadedAt: Date.now(),
            status: "error_processing",
            error:
              fileError instanceof Error ? fileError.message : "Unknown error",
          };
        }
      }),
    );

    // Check if any files failed
    const successCount = results.filter((r) => r.status === "success").length;
    const failedCount = results.length - successCount;

    return NextResponse.json({
      success: successCount > 0,
      data: results,
      message:
        failedCount === 0
          ? `Successfully uploaded ${successCount} file(s)`
          : `Uploaded ${successCount} file(s), ${failedCount} failed`,
      successCount,
      failedCount,
      totalCount: results.length,
    });
  } catch (error) {
    logger.error("Error uploading files to knowledge:", error);
    return NextResponse.json(
      {
        error: "Failed to upload files",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}

export const POST = withRateLimit(handlePOST, RateLimitPresets.STANDARD);
