import { NextRequest, NextResponse } from "next/server";
import { requireAuthOrApiKey } from "@/lib/auth";
import { agentRuntime } from "@/lib/eliza/agent-runtime";
import { getKnowledgeService } from "@/lib/eliza/knowledge-service";
import type { UUID } from "@elizaos/core";
import { stringToUuid } from "@elizaos/core";
import { withRateLimit, RateLimitPresets } from "@/lib/middleware/rate-limit";

export const maxDuration = 60;

interface UploadResult {
  id: string;
  filename: string;
  type: string;
  size: number;
  uploadedAt: number;
  status: string;
  fragmentCount?: number;
  error?: string;
}

/**
 * POST /api/v1/knowledge/upload-file - Upload files to knowledge base
 * Handles multiple files matching plugin-knowledge pattern
 */
async function handlePOST(req: NextRequest) {
  try {
    const { user } = await requireAuthOrApiKey(req);
    const runtime = await agentRuntime.getRuntime();
    const knowledgeService = await getKnowledgeService(runtime);

    if (!knowledgeService) {
      return NextResponse.json(
        { error: "Knowledge service not available" },
        { status: 503 },
      );
    }

    const formData = await req.formData();
    const files = formData.getAll("files") as File[];

    if (!files || files.length === 0) {
      return NextResponse.json({ 
        error: "No files provided",
        details: "Please upload at least one file" 
      }, { status: 400 });
    }

    // Process all files
    const results: UploadResult[] = await Promise.all(
      files.map(async (file) => {
        try {
          // Read file content and convert to base64
          const arrayBuffer = await file.arrayBuffer();
          const buffer = Buffer.from(arrayBuffer);
          const base64Content = buffer.toString("base64");
          const contentType = file.type || "application/octet-stream";

          // Add knowledge document (matching plugin-knowledge pattern exactly)
          // Use runtime.agentId for roomId, worldId, entityId (same as plugin)
          const result = await knowledgeService.addKnowledge({
            agentId: runtime.agentId,
            clientDocumentId: "" as UUID, // Auto-generated by service
            content: base64Content,
            contentType,
            originalFilename: file.name,
            worldId: runtime.agentId,
            roomId: runtime.agentId,
            entityId: runtime.agentId,
            metadata: {
              uploadedBy: user.id,
              uploadedAt: Date.now(),
              organizationId: user.organization_id,
              fileSize: file.size,
              fileName: file.name,
              filename: file.name, // Add both for compatibility
            },
          });

          return {
            id: result.clientDocumentId,
            filename: file.name,
            type: contentType,
            size: file.size,
            uploadedAt: Date.now(),
            fragmentCount: result.fragmentCount,
            status: "success",
          };
        } catch (fileError) {
          console.error(`Error processing file ${file.name}:`, fileError);
          return {
            id: "",
            filename: file.name,
            type: file.type,
            size: file.size,
            uploadedAt: Date.now(),
            status: "error_processing",
            error: fileError instanceof Error ? fileError.message : "Unknown error",
          };
        }
      })
    );

    // Check if any files failed
    const successCount = results.filter(r => r.status === "success").length;
    const failedCount = results.length - successCount;

    return NextResponse.json({
      success: successCount > 0,
      data: results,
      message: failedCount === 0 
        ? `Successfully uploaded ${successCount} file(s)` 
        : `Uploaded ${successCount} file(s), ${failedCount} failed`,
      successCount,
      failedCount,
      totalCount: results.length,
    });
  } catch (error) {
    console.error("Error uploading files to knowledge:", error);
    return NextResponse.json(
      {
        error: "Failed to upload files",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}

export const POST = withRateLimit(handlePOST, RateLimitPresets.STANDARD);
